pipeline {
    agent any
    stages {
        stage('Clone The Repository') {
            steps {
                git 'https://github.com/rajshamz/simple-quiz-app.git'
            }
        }
        stage('Build Docker Container') {
            steps {
                script {
                    def app = docker.build("quiz-app:latest", ".")
                }
            }
        }
        stage('Deploy to Docker Host') {
            steps {
                withDockerHost([
                    url: 'unix:///var/run/docker.sock'

                ]) {
                    script {
                        docker.image("quiz-app:latest").push("latest")
                    }
                }
            }
        }
    }
}
